# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: D:\Cipherxzc\Projects\yolo\datasets\wider_face  # dataset root dir
train: train/labels  # train images (relative to 'path') 12876 images
val: val/labels  # val images (relative to 'path') 3226 images
test:  # test images (optional)

# Classes
names:
  0: face
 
# Download script/URL (optional)
download: